/-
Copyright (c) 2026 Álvaro Begué. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Álvaro Begué
-/
import CSP.Bridge
import ZhukLean.Central

/-!
# The six types of strong subuniverse

Zhuk's relations `C <_T^A B` for `T ∈ {BA, C, S, D, L, PC}`, the multi-types `ℳT`, and the
strong-reduction relation `C ⋘^A B`.

Two design points, both argued in the blueprint:

* `⋘` is `Relation.ReflTransGen` of the union of the four base relations
  (`haz:lll-chain`).  The induction principle that comes with `ReflTransGen` is exactly
  the one the proofs use, and `L`/`PC` are absent from the union because `D` subsumes them.
* the dotted variants are *defined* as `C = ∅ ∨ (undotted)`, so that the case split is
  forced at every use site (`haz:dot`).

Absorption is reused verbatim from the predecessor development: `ZhukLean.Absorbs`,
`ZhukLean.BinAbsorbs` and `ZhukLean.centralPairs` are stated in the tuple form that
`haz:absorption-tuples` insists on.

## Blueprint

`ch3-types.tex`.
-/

open FirstOrder Language ZhukLean

universe u v w

namespace CSP

variable {L : Language.{u, v}} {A : Type w} [L.Structure A]

/-! ### Central subuniverses, relative form -/

/-- `C` is a central subuniverse of `B`: it absorbs `B`, and no element of `B ∖ C` has its
diagonal generated by the two off-diagonal blocks.  Blueprint `def:central`.

`ZhukLean.CentrallyAbsorbs` is the special case `B = univ`; Zhuk's `<_C` needs the
relative version. -/
structure IsCentralIn (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop where
  absorbs : Absorbs L C B
  central : ∀ a ∈ B, a ∉ C → ((a, a) : A × A) ∉ Substructure.closure L (centralPairs C a)

theorem IsCentralIn.of_centrallyAbsorbs {C : Set A} (h : CentrallyAbsorbs L C) :
    IsCentralIn L C Set.univ where
  absorbs := h.absorbs
  central a _ ha := h.central a ha

/-- An algebra (or subset) is **BA and centre free** if it has no nonempty proper binary
absorbing or central subuniverse.  Blueprint `def:ba-center-free`. -/
def BACenterFree (L : Language.{u, v}) [L.Structure A] (B : Set A) : Prop :=
  ∀ C : Set A, C.Nonempty → C ⊂ B → ¬ BinAbsorbs L C B ∧ ¬ IsCentralIn L C B

/-- `B` is **S-free** if no nonempty proper subset is simultaneously binary absorbing and
central in it.  Note this is a *conjunction*, unlike `<_S` itself — see `haz:S-type`. -/
def SFree (L : Language.{u, v}) [L.Structure A] (B : Set A) : Prop :=
  ∀ C : Set A, C.Nonempty → C ⊂ B → ¬ (BinAbsorbs L C B ∧ IsCentralIn L C B)

theorem SFree.of_baCenterFree {B : Set A} (h : BACenterFree L B) : SFree L B :=
  fun C hne hlt hcon => (h C hne hlt).1 hcon.1

/-! ### Blocks -/

/-- `E` is a block of the congruence `σ`. -/
def IsBlock (σ : Congruence L A) (E : Set A) : Prop := ∃ a : A, E = {b | σ a b}

theorem isBlock_class (σ : Congruence L A) (a : A) : IsBlock σ {b | σ a b} := ⟨a, rfl⟩

/-! ### The six types -/

/-- Zhuk's `C <_BA^A B`. -/
def SubBA (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  C.Nonempty ∧ C ⊂ B ∧ BinAbsorbs L C B

/-- Zhuk's `C <_C^A B`. -/
def SubC (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  C.Nonempty ∧ C ⊂ B ∧ IsCentralIn L C B

/-- Zhuk's `C <_S^A B`: `C` *contains* a subset that is simultaneously binary absorbing
and central in `B`.  It is deliberately not the conjunction of `SubBA` and `SubC`; see
`haz:S-type`. -/
def SubS (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  C.Nonempty ∧ C ⊂ B ∧ ∃ D : Set A, D.Nonempty ∧ D ⊆ C ∧ BinAbsorbs L D B ∧ IsCentralIn L D B

/-- Zhuk's `C <_D^A B` with the witnessing congruence exposed.  The three conditions are:
`B` lies inside one block of `σ*`; `C` is the trace on `B` of a block of `σ`; and the
quotient `B/σ` is BA and centre free. -/
structure SubDWith (L : Language.{u, v}) [L.Structure A] (σ : Congruence L A)
    (C B : Set A) : Prop where
  nonempty : C.Nonempty
  lt : C ⊂ B
  irred : Irreducible σ
  /-- `B² ⊆ σ*`. -/
  inside_cover : ∀ δ, IsCover σ δ → ∀ a ∈ B, ∀ b ∈ B, (a, b) ∈ δ
  /-- `C = B ∩ E` for a block `E` of `σ`. -/
  trace : ∃ E, IsBlock σ E ∧ C = B ∩ E
  /-- `B/σ` is BA and centre free. -/
  quot_free : BACenterFree L (σ.proj '' B)

/-- Zhuk's `C <_D^A B`. -/
def SubD (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  ∃ σ : Congruence L A, SubDWith L σ C B

/-- Zhuk's `C <_L^A B`: dividing, with a *linear* witnessing congruence. -/
def SubL (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  ∃ σ : Congruence L A, SubDWith L σ C B ∧ IsLinear σ

/-- Zhuk's `C <_PC^A B`: dividing, with a *PC* witnessing congruence. -/
def SubPC (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  ∃ σ : Congruence L A, SubDWith L σ C B ∧ IsPC σ

theorem SubD.of_subL {C B : Set A} (h : SubL L C B) : SubD L C B :=
  let ⟨σ, hσ, _⟩ := h; ⟨σ, hσ⟩

theorem SubD.of_subPC {C B : Set A} (h : SubPC L C B) : SubD L C B :=
  let ⟨σ, hσ, _⟩ := h; ⟨σ, hσ⟩

/-! ### Multi-types -/

/-- Zhuk's `C ≤_{ℳT}^A B`: a nonempty intersection of finitely many type-`T` subsets. -/
def SubMulti (T : Set A → Set A → Prop) (C B : Set A) : Prop :=
  C.Nonempty ∧ ∃ (ι : Type w) (_ : Finite ι) (f : ι → Set A),
    (∀ i, T (f i) B) ∧ C = ⋂ i, f i

/-! ### The strong-reduction relation `⋘` -/

/-- One step of `⋘`: a reduction of any of the four base types.  `L` and `PC` are omitted
because `D` subsumes them (`haz:lll-chain`). -/
def SubStep (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  SubBA L C B ∨ SubC L C B ∨ SubS L C B ∨ SubD L C B

/-- **Zhuk's `C ⋘^A B`**: reachability by a chain of strong reductions.  Reflexive by
construction, and its induction principle is `Relation.ReflTransGen.head_induction_on`. -/
def Lll (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  Relation.ReflTransGen (fun X Y => SubStep L Y X) B C

theorem Lll.refl (B : Set A) : Lll L B B := Relation.ReflTransGen.refl

theorem Lll.trans {C B D : Set A} (h₁ : Lll L C B) (h₂ : Lll L D C) : Lll L D B :=
  Relation.ReflTransGen.trans h₁ h₂

theorem Lll.of_step {C B : Set A} (h : SubStep L C B) : Lll L C B :=
  Relation.ReflTransGen.single h

theorem Lll.of_subBA {C B : Set A} (h : SubBA L C B) : Lll L C B :=
  Lll.of_step (Or.inl h)

theorem Lll.of_subD {C B : Set A} (h : SubD L C B) : Lll L C B :=
  Lll.of_step (Or.inr (Or.inr (Or.inr h)))

/-- The dotted variant: the relation holds, or the left-hand side is empty.  Defined so
that the case split is forced at every use site (`haz:dot`). -/
def DotLll (L : Language.{u, v}) [L.Structure A] (C B : Set A) : Prop :=
  C = ∅ ∨ Lll L C B

theorem DotLll.of_lll {C B : Set A} (h : Lll L C B) : DotLll L C B := Or.inr h

/-! ### Basic consequences -/

/-- Every one-step reduction shrinks the set.  This is the source of the well-founded
measure of `haz:the-induction`: on a finite algebra, `|C| < |B|` at every step. -/
theorem SubStep.subset {C B : Set A} (h : SubStep L C B) : C ⊂ B := by
  rcases h with h | h | h | ⟨σ, h⟩
  · exact h.2.1
  · exact h.2.1
  · exact h.2.1
  · exact h.lt

theorem Lll.subset {C B : Set A} (h : Lll L C B) : C ⊆ B := by
  induction h with
  | refl => exact subset_rfl
  | tail _ hstep ih => exact (SubStep.subset hstep).subset.trans ih

end CSP
